//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silmoon.Web {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class js {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal js() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Silmoon.Web.js", typeof(js).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 
        ///function _ajax_on_complete(senderId, e, onSuccess, onFailed, onError) {
        ///    if (e.readyState == 4) {
        ///        var obj = JSON.parse(e.responseText);
        ///        if (obj.Success) {
        ///            $(&quot;#&quot; + senderId).html(&apos;成功&apos;);
        ///            if (onSuccess != null) onSuccess(senderId, e);
        ///        } else {
        ///            $(&quot;#&quot; + senderId).html(&apos;失败&apos;)
        ///            if (onFailed != null) onFailed(senderId, e);
        ///        }
        ///    }
        ///    else {
        ///        $(&quot;#&quot; + senderId).html(&apos;错误&apos;)
        ///        if (onError != null) onError(sender [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ajaxOptionFunctions
        {
            get
            {
                return ResourceManager.GetString("ajaxOptionFunctions", resourceCulture);
            }
        }
        public static string ajaxOptionFunctionsV1
        {
            get
            {
                return ResourceManager.GetString("ajaxOptionFunctionsV1", resourceCulture);
            }
        }

        public static string ajaxOptionFunctionsV2
        {
            get
            {
                return ResourceManager.GetString("ajaxOptionFunctionsV2", resourceCulture);
            }
        }
    }
}
